compile wireguard tools/module, make it optional

diff --git a/root/etc/cont-init.d/30-config b/root/etc/cont-init.d/30-config
--- a/root/etc/cont-init.d/30-config
+++ b/root/etc/cont-init.d/30-config
@@ -2,83 +2,113 @@
 
 mkdir -p /config/{templates,coredns}
 
-# install headers and wireguard
-apt-get update
-if apt-cache show linux-headers-$(uname -r) 2&>1 >/dev/null; then
-  apt-get install -y \
-    linux-headers-$(uname -r) \
-    wireguard
-elif (uname -r | grep -q 'v7+') || (uname -r | grep -q 'v7l+') || (uname -r | grep -q 'v8+'); then
-  echo "Raspbian kernel naming convention detected, attempting to install raspbian kernel headers"
-  curl -s http://archive.raspberrypi.org/debian/raspberrypi.gpg.key | apt-key add -
-  echo -e \
-    "deb http://archive.raspberrypi.org/debian/ buster main\ndeb-src http://archive.raspberrypi.org/debian/ buster main" \
-    > /etc/apt/sources.list.d/raspbian.list
-  apt-get update
-  apt-get install -y \
-    raspberrypi-kernel-headers \
-    wireguard
-elif uname -v | grep -q 'Ubuntu'; then
-  echo "Attempting to install kernel headers from Ubuntu Xenial repo"
-  echo -e \
-    "deb http://archive.ubuntu.com/ubuntu/ xenial main restricted\ndeb-src http://archive.ubuntu.com/ubuntu/ xenial main restricted\n\ndeb http://archive.ubuntu.com/ubuntu/ xenial-updates main restricted\ndeb-src http://archive.ubuntu.com/ubuntu/ xenial-updates main restricted" \
-    > /etc/apt/sources.list.d/xenial.list
-  apt-get update
-  if apt-cache show linux-headers-$(uname -r) 2&>1 >/dev/null; then
-    apt-get install -y \
-      linux-headers-$(uname -r) \
-      wireguard
+# check for wireguard module
+if grep -q wireguard /proc/modules; then
+  echo "It seems the wireguard module is already loaded, let's test to make sure it works."
+  /app/wireguard-tools/contrib/ncat-client-server/client-quick.sh
+  wg-quick up demo
+  if wg show | grep -q demo; then
+    echo "The module is working properly, skipping kernel header install and module compilation."
+    SKIP_COMPILE="true"
   else
-    echo "No kernel headers found in the Ubuntu repos!! Will try the headers from host (if mapped), may or may not work"
-    apt-get install -y \
-      wireguard
+    echo "The module is not functional, will attempt kernel header install and module compilation."
   fi
-elif uname -v | grep -q 'Debian'; then
-  echo "Debian host detected, attempting to install kernel headers from Debian Buster repo"
-  curl -s https://ftp-master.debian.org/keys/archive-key-10.asc | apt-key add -
-  echo -e \
-    "deb http://deb.debian.org/debian buster main contrib non-free\ndeb-src http://deb.debian.org/debian buster main contrib non-free\ndeb http://deb.debian.org/debian buster-backports main contrib non-free\ndeb-src http://deb.debian.org/debian buster-backports main contrib non-free" \
-    > /etc/apt/sources.list.d/debian.list
+  wg-quick down demo
+  rm -f /etc/wireguard/demo.conf
+else
+  echo "The wireguard module is not loaded, will attempt kernel header install and module compilation."
+fi  
+
+# install headers if necessary
+if [ "$SKIP_COMPILE" != "true" ]; then
+  echo "Attempting kernel header install"
   apt-get update
   if apt-cache show linux-headers-$(uname -r) 2&>1 >/dev/null; then
-    if uname -r | grep -qs "bpo"; then
-      echo "Backported kernel detected"
-      apt-get install -y -t buster-backports \
+    apt-get install -y \
+      linux-headers-$(uname -r)
+  elif (uname -r | grep -q 'v7+') || (uname -r | grep -q 'v7l+') || (uname -r | grep -q 'v8+'); then
+    echo "Raspbian kernel naming convention detected, attempting to install raspbian kernel headers"
+    curl -s http://archive.raspberrypi.org/debian/raspberrypi.gpg.key | apt-key add -
+    echo -e \
+      "deb http://archive.raspberrypi.org/debian/ buster main\ndeb-src http://archive.raspberrypi.org/debian/ buster main" \
+      > /etc/apt/sources.list.d/raspbian.list
+    apt-get update
+    apt-get install -y \
+      raspberrypi-kernel-headers
+  elif uname -v | grep -q 'Ubuntu'; then
+    echo "Attempting to install kernel headers from Ubuntu Xenial repo"
+    echo -e \
+      "deb http://archive.ubuntu.com/ubuntu/ xenial main restricted\ndeb-src http://archive.ubuntu.com/ubuntu/ xenial main restricted\n\ndeb http://archive.ubuntu.com/ubuntu/ xenial-updates main restricted\ndeb-src http://archive.ubuntu.com/ubuntu/ xenial-updates main restricted" \
+      > /etc/apt/sources.list.d/xenial.list
+    apt-get update
+    if apt-cache show linux-headers-$(uname -r) 2&>1 >/dev/null; then
+      apt-get install -y \
         linux-headers-$(uname -r)
-      apt-get install -y \
-        wireguard
     else
-      apt-get install -y \
-        linux-headers-$(uname -r) \
-        wireguard
+      echo "No kernel headers found in the Ubuntu repos!! Will try the headers from host (if mapped), may or may not work"
     fi
-  else
-    echo "Attempting to install kernel headers from the Debian Stretch repo"
-    curl -s https://ftp-master.debian.org/keys/archive-key-9.asc | apt-key add -
-    sed -i 's/buster/stretch/g' /etc/apt/sources.list.d/debian.list
+  elif uname -v | grep -q 'Debian'; then
+    echo "Debian host detected, attempting to install kernel headers from Debian Buster repo"
+    curl -s https://ftp-master.debian.org/keys/archive-key-10.asc | apt-key add -
+    echo -e \
+      "deb http://deb.debian.org/debian buster main contrib non-free\ndeb-src http://deb.debian.org/debian buster main contrib non-free\ndeb http://deb.debian.org/debian buster-backports main contrib non-free\ndeb-src http://deb.debian.org/debian buster-backports main contrib non-free" \
+      > /etc/apt/sources.list.d/debian.list
     apt-get update
     if apt-cache show linux-headers-$(uname -r) 2&>1 >/dev/null; then
       if uname -r | grep -qs "bpo"; then
         echo "Backported kernel detected"
-        apt-get install -y -t stretch-backports \
+        apt-get install -y -t buster-backports \
           linux-headers-$(uname -r)
-        apt-get install -y \
-          wireguard
       else
         apt-get install -y \
-          linux-headers-$(uname -r) \
-          wireguard
+          linux-headers-$(uname -r)
       fi
     else
-      echo "No kernel headers found in Debian repos!! Will try the headers from host (if mapped), may or may not work"
-      apt-get install -y \
-        wireguard
+      echo "Attempting to install kernel headers from the Debian Stretch repo"
+      curl -s https://ftp-master.debian.org/keys/archive-key-9.asc | apt-key add -
+      sed -i 's/buster/stretch/g' /etc/apt/sources.list.d/debian.list
+      apt-get update
+      if apt-cache show linux-headers-$(uname -r) 2&>1 >/dev/null; then
+        if uname -r | grep -qs "bpo"; then
+          echo "Backported kernel detected"
+          apt-get install -y -t stretch-backports \
+            linux-headers-$(uname -r)
+        else
+          apt-get install -y \
+            linux-headers-$(uname -r)
+        fi
+      else
+        echo "No kernel headers found in Debian repos!! Will try the headers from host (if mapped), may or may not work"
+      fi
     fi
+  else
+    echo "No kernel headers found in the Ubuntu or Debian repos!! Will try the headers from host (if mapped), may or may not work"
   fi
-else
-  echo "No kernel headers found in the Ubuntu or Debian repos!! Will try the headers from host (if mapped), may or may not work"
-  apt-get install -y \
-    wireguard
+fi
+
+if [ "$SKIP_COMPILE" != "true" ]; then
+  if [ -e /lib/modules/$(uname -r)/build ]; then 
+    echo "Kernel headers seem to be present, attempting to build the wireguard module. . ."
+    cd /app
+    make -C wireguard-linux-compat/src -j$(nproc)
+    make -C wireguard-linux-compat/src install
+    echo "Let's test our new module."
+    /app/wireguard-tools/contrib/ncat-client-server/client-quick.sh
+    wg-quick up demo
+    if wg show | grep -q demo; then
+      echo "The module is working properly, moving forward with setup."
+    else
+      echo "The module is not working, review the logs. Sleeping now. . ."
+      wg-quick down demo
+      rm -f /etc/wireguard/demo.conf
+      sleep infinity
+    fi
+    wg-quick down demo
+    rm -f /etc/wireguard/demo.conf
+  else
+    echo "Kernel headers don't seem to be available, can't compile the module. Sleeping now. . ."
+    sleep infinity
+  fi
 fi
 
 # prepare symlinks
